class StrangeUseOfTheDecorator(Exception):
    ...

class TooManyPluginsError(Exception):
    ...

class PrimadonnaPluginError(Exception):
    ...

class StrangeTypeAnnotationError(Exception):
    ...
